#Admin
#These routes are prefix with /admin/banners in routing.yml
nfq_banner_list:
    path: /
    methods: [ GET ]
    defaults: { _controller: NfqBannerBundle:Admin/Banner:index }

nfq_banner_new:
    path: /new
    methods: [ GET ]
    defaults: { _controller: NfqBannerBundle:Admin/Banner:new }

nfq_banner_create:
    path: /new
    methods: [ POST ]
    defaults: { _controller: NfqBannerBundle:Admin/Banner:create }

nfq_banner_update:
    path: /{id}/update
    methods: [ GET, POST ]
    defaults: { _controller: NfqBannerBundle:Admin/Banner:update }

nfq_banner_delete:
    path: /{id}/delete
    methods: [ GET, POST ]
    defaults: { _controller: NfqBannerBundle:Admin/Banner:delete }
